replicaCount: 1
image:
  repository: 10.91.245.115:5000/cong-xiu/jx-micronaut-seed
  tag: 0.2.0
  pullPolicy: IfNotPresent
env: null
knativeDeploy: false
service:
  name: jenkins-x-kubernetes
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: 'kubernetes.io/ingress.class: nginx'
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 400m
    memory: 512Mi
probePath: /health
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10
jenkins-x-kubernetes-redis:
  usePassword: false
